#!/bin/bash

# Clear existing variables first
unset ANTHROPIC_MODEL
unset ANTHROPIC_SMALL_FAST_MODEL
unset ANTHROPIC_BASE_URL
unset ANTHROPIC_AUTH_TOKEN

# Export variables
export ANTHROPIC_MODEL='claude-3-7-sonnet-20250219'
export ANTHROPIC_SMALL_FAST_MODEL='claude-3-5-haiku-20241022'
export ANTHROPIC_BASE_URL='http://localhost:3000'
export ANTHROPIC_AUTH_TOKEN=''

# Verify exports
echo "🔄 Checking environment variables..."
printenv | grep ANTHROPIC_

curl -X POST http://localhost:3000/v1/messages \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $ANTHROPIC_AUTH_TOKEN" \
        -d '{
          "model": "deepseek-r1-v1",
          "messages": [
            {
              "role": "user",
              "content": "Hello?Who are you?"
            }
          ],
          "max_tokens": 1024
 }'


export ECR_REPO=$(aws ecr describe-repositories --repository-names "infinite-pi/chatrix" --region us-west-2 --query 'repositories[0].repositoryUri' --output text)
aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $ECR_REPO
docker tag chatrix:latest $ECR_REPO:latest
docker push $ECR_REPO:latest